export enum UserType {
  ROLE_INDIVIDUAL = 'ROLE_INDIVIDUAL',
  ROLE_COMPANY = 'ROLE_COMPANY',
  ROLE_COMPANY_SOFTWARE = 'ROLE_COMPANY_SOFTWARE'
}
// export enum CompanyType {
//   ROLE_COMPANY = 'ROLE_COMPANY',
//   ROLE_COMPANY_SOFTWARE = 'ROLE_COMPANY_SOFTWARE'
// }
